// tag::FEEDBACK[]
:filename: 01-module-block-1/01-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: 180 Min. | Übungszeit: 60 Min.
|===

Diese Lerneinheit führt in die grundlegenden Elemente der Struktur
funktionaler Software-Systeme ein: Reine Funktionen operieren auf
unveränderlichen Werten. Dies steht im Gegensatz zum objektorientierten
Modell, in dem Methoden auf gekapseltem Zustand operieren. Diese
Funktionen werden zu domänenrelevanter Funktionalität miteinander
kombiniert beziehungsweise _komponiert._ Der Entwurf von Funktionen und
ihre Komposition wird von ihren Typsignaturen getrieben. Anders als in
der objektorientierten Architektur sind Funktionen nicht an Klassen
gebunden, sondern werden in Modulen gebündelt.

=== Begriffe und Konzepte
* Funktionen und Werte
* Komposition
* Typen
* Module

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 180 min | Exercises: 60 min
|===

=== Terms and concepts
* Term 1
* Term 2
* Term 3
// end::EN[]


// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
