// tag::DE[]
|===
| Dauer: 180 Min. | Übungszeit: 120 Min.
|===

Diese Lerneinheit führt in die grundlegenden Elemente der Struktur
funktionaler Software-Systeme ein: Reine Funktionen operieren auf
unveränderlichen Werten. Dies steht im Gegensatz zum objektorientierten
Modell, in dem Methoden auf gekapseltem Zustand operieren. Diese
Funktionen werden zu domänenrelevanter Funktionalität miteinander
kombiniert beziehungsweise _komponiert._ Der Entwurf von Funktionen und
ihre Komposition wird von ihren Typsignaturen getrieben. Anders als in
der objektorientierten Architektur sind Funktionen nicht an Klassen
gebunden, sondern werden in Modulen gebündelt.

=== Begriffe und Konzepte
Werte, Funktionen, Komposition, Typen, Module

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 180 min | Exercises: 120 min
|===

This section introduces the basic elements of the structure of
functional software systems: Pure functions operate on immutable values.
This is in contrast to the object-oriented model, where methods operate
on an encapsulated state. These functions are combined or _composed_
into domain-relevant functionality. The design of functions and their
composition is driven by their type signatures. In functional
architecture, functions are bundled in modules, as opposed to
object-oriented programming where they are bundled with classes.

=== Terms and concepts
Values, Functions, Composition, Types, Modules
// end::EN[]

