= Curriculum for https://isaqb.org[iSAQB] Advanced Level Module FUNAR

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status

image:https://github.com/isaqb-org/curriculum-funar/workflows/CI/badge.svg?branch=master["CI"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-funar/master.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-funar.svg["Contributors",link="https://github.com/isaqb-org/curriculum-funar/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-funar.svg["Issues",link="https://github.com/isaqb-org/curriculum-funar/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-funar.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-funar/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the curriculum for the https://www.isaqb.org/certifications/advanced-level/[iSAQB Advanced Level] module *FUNAR*.
The curriculum is generated from Asciidoc files in the `docs` subfolder.

New official revisions of the curriculum will be published via the https://github.com/isaqb-org/curriculum-funar/releases[Github Releases] features.

For more information on the iSAQB or the Certified Professional for Software Architecture certification program, please visit https://isaqb.org.

== How to contribute or participate

If you find issues or have questions on this curriculum, please create an issue or pull-request.

For more information on How to use this template, please see https://github.com/isaqb-org/advanced-template


== How to create the output documents

.Prerequisite:
You need a Java(tm) Runtime Environment installed on your machine.

.Creating the PDFs
The output documents (HTML + PDF) are build with https://gradle.org[gradle].
You can start a build locally when you run `./gradlew buildDocs` inside the cloned repository folder.
If you don't modify the configuration, this build will create pdf and html output in German (DE) _and_ English (EN) with and without remarks.


== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by
https://github.com/mikesperber[Mike Sperber].
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::LICENSE.adoc[]
