// tag::FEEDBACK[]
:filename: 03-module-block-3/01-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: 180 Min. | Übungszeit: 60 Min.
|===

Dieser Abschnitt behandelt inhärent funktionale Ansätze, um funktionale
Anforderungen in Software-Architektur umzusetzen. Domain-driven Design
kann mit funktionaler Programmierung statt objektorientierter
Programmierung umgesetzt werden. Kombinatormodelle decken verstecktes
Domänenwissen auf. Eingebettete domänenspezifische Sprachen ermöglichen
einen schnellen Abgleich von Anforderungen und Architektur.

=== Begriffe und Konzepte
* funktionale Anforderungen
* DDD
* Kombinatormodelle
* eingebettete domänenspezifische Sprachen

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 180 min | Exercises: 60 min
|===

This section discusses inherently functional approaches to translating
functional requirements into software architecture. Domain-driven design
can be implemented with functional programming instead of
object-oriented programming. Combinator models reveal hidden domain
knowledge. Embedded domain-specific languages allow fast alignment of
requirements and architecture.

=== Terms and concepts
* functional requirements
* DDD
* combinator models
* embedded domain-specific languages.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
