// tag::FEEDBACK[]
:filename: 03-module-block-3/01-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: 180 Min. | Übungszeit: 60 Min.
|===

Dieser Abschnitt behandelt inhärent funktionale Ansätze, um funktionale
Anforderungen in Software-Architektur umzusetzen. Domain-driven Design
kann mit funktionaler Programmierung statt objektorientierter
Programmierung umgesetzt werden. Kombinatormodelle decken verstecktes
Domänenwissen auf. Eingebettete domänenspezifische Sprachen ermöglichen
einen schnellen Abgleich von Anforderungen und Architektur.

=== Begriffe und Konzepte
* funktionale Anforderungen
* DDD
* Kombinatormodelle
* eingebettete domänenspezifische Sprachen

// end::DE[]

// tag::EN[]
|===
| Lesson duration: XXX min | Exercises: XXX min
|===

=== Terms and concepts
* Term 1
* Term 2
* Term 3
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
