// tag::DE[]
|===
| Dauer: 120 Min. | Übungszeit: Keine.
|===

Funktionale Software-Architektur ist in der Regel verbunden mit der
Verwendung funktionaler Programmiersprachen und Frameworks. Dieser
Abschnitt gibt einen Überblick über die wichtigsten Eigenschaften und
Beschränkungen verfügbarer Technologien, um Architektinnen die
Entscheidung für oder gegen eine Technologie zu ermöglichen.

=== Begriffe und Konzepte

statische Typen, dynamische Typen, Endrekursion, strikte bzw. nicht-strikte Auswertung, Laufzeitumgebung

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 120 min | Exercises: None
|===

Functional software architecture is usually associated with the use of
functional programming languages and frameworks. This section provides
an overview of the key features and limitations of available
technologies to enable architects to decide for or against a technology.

=== Terms and concepts
static types, dynamic types, tail recursion, strict or non-strict evaluation, runtime environment.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
