// tag::FEEDBACK[]
:filename: 02-module-block-2/01-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: 120 Min. | Übungszeit: Keine.
|===

Funktionale Software-Architektur ist in der Regel verbunden mit der
Verwendung funktionaler Programmiersprachen und Frameworks. Dieser
Abschnitt gibt einen Überblick über die wichtigsten Eigenschaften und
Beschränkungen verfügbarer Technologien, um Architektinnen die
Entscheidung für oder gegen eine Technologie zu ermöglichen.

=== Begriffe und Konzepte

* statische Typen
* dynamische Typen
* Endrekursion
* strikte bzw. nicht-strikte Auswertung
* Laufzeitumgebung

// end::DE[]

// tag::EN[]
|===
| Lesson duration: XXX min | Exercises: XXX min
|===

=== Terms and concepts
* Term 1
* Term 2
* Term 3
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
