// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Das Modul präsentiert den Teilnehmerinnen funktionale
Software-Architektur als Alternative zu objektorientierter Architektur.
Im Vergleich zu OO-Architektur setzt die funktionale
Software-Architektur auf unveränderliche Daten, algebraische
Abstraktionen und eingebettete domänenspezifische Sprachen. Das Resultat
sind flexible und robuste Architekturen, die gegenüber OO weniger
komplex sind und weniger versteckte Abhängigkeiten mit sich
bringen.footnote:[Die Vergleiche zu objektorientierter
Software-Architektur tragen dem Umstand Rechnung, dass die Autoren davon
ausgehen, die meisten potenziellen Teilnehmer an einer Advanced-Schulung
mit objektorientierter Software-Architektur vertraut sind. Für die
Schulung essenziell ist dieser Vergleich allerdings nicht und kann
zugunsten einer Vertiefung der (eh reichlichen) Inhalte auch entfallen.]

Anders als bei OO-Architekturen sind FP-Architekturen direkt Code. In
diesem Modul können deshalb alle Architekturprinzipien durch konkreten
Code illustriert werden und sind damit anschaulich
erlernbar.footnote:[Eine Reihe von Sprachen kommt für die Begleitung
einer solchen Schulung in Betracht. Besonders geeignet können Haskell
und Racket sein, die alle Architekturprinzipien dieses Lehrplans direkt
unterstützen. Racket mag sich besonders gut für Schulungen eignen, denen
eine Einführung in die funktionale Programmierung mit den dort
eingebauten Lehrsprachen vorangeht.]

Nach Abschluss des Moduls kennen die Teilnehmerinnen die wesentlichen
Prinzipien funktionaler Architektur und können diese beim Entwurf von
Software-Systemen anwenden. Sie kennen die Eigenheiten funktionaler
Programmiersprachen und können diese bei der Implementierung von
Software-Systemen effektiv ausnutzen. Sie können Domänenwissen direkt in
ausführbaren Code umwandeln und daraus systematisch algebraische
Abstraktionen entwickeln.
// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

The module presents functional software architecture as an alternative
to object-oriented architecture. Compared to OO architecture, functional
software architecture relies on immutable data, algebraic abstractions
and embedded domain-specific languages. The result are flexible and
robust architectures that are less complex and have fewer hidden
dependencies than OO.footnote:[The comparisons to object-oriented
software architecture take into account the fact that the authors assume
that most potential participants in an advanced training course are
familiar with object-oriented software architecture. However, this
comparison is not essential for the training course and can be omitted
in favor of a more in-depth study of the (already abundant) contents.]

Unlike OO architectures, FP architectures are entirely code. This module
therefore illustrates all architectural principles with concrete code,
making them easier to learn.footnote:[A number of languages can be used
to accompany such a training course. Haskell and Racket can be
particularly suitable, as they directly support all the architectural
principles of this curriculum. Racket may be particularly suitable for
training courses that follow an introduction to functional programming
with the built-in teaching languages.]

After completion of the module, participants will know the essential
principles of functional architecture and will be able to apply them
when designing software systems. They will know the peculiarities of
functional programming languages and can use them effectively when
implementing software systems. They can convert domain knowledge
directly into executable code and systematically use this to develop
algebraic abstractions.
// end::EN[]

