// tag::FEEDBACK[]
:filename: 05-module-block-5/01-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: 180 Min. | Übungszeit: 60 Min.
|===

In der funktionalen Software-Architektur gibt es spezifische
Architekturmuster. Dazu gehört die Verwendung performanter funktionaler
Datenstrukturen, die Verwendung algebraischer Abstraktionen und die
UI-Entwicklung mit dem Model-View-Update-Pattern als Gegenmodell zu
Model-View-Controller.

=== Begriffe und Konzepte
* funktionale Datenstruktur
* Monoid
* Funktor
* Monade
* Model-View-Update

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 180 min | Exercises: 60 min
|===

Functional software architecture has specific architectural patterns.
These include the use of high-performance functional data structures,
the use of algebraic abstractions and UI development with the
Model-View-Update Pattern as an alternative to Model-View-Controller.

=== Terms and concepts
* functional data structure
* monoid
* functor
* monad
* Model-View-Update.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
